/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.myHome;

public class App {
    public String getGreeting() {
        return "Hello, Java!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
